#!/bin/bash

touch .env
"NOREPLY_EMAIL_ADDRESS=${{secrets.NOREPLY_EMAIL_ADDRESS}}" \
"NOREPLY_EMAIL_PASSWORD=${{secrets.NOREPLY_EMAIL_PASSWORD}}" \
"NOREPLY_EMAIL_SMTP_ADDRESS=${{secrets.NOREPLY_EMAIL_SMTP_ADDRESS}}" \
"NOREPLY_EMAIL_SMTP_PORT=${{secrets.}}" \
"INFO_EMAIL_ADDRESS=${{secrets.INFO_EMAIL_ADDRESS}}" \
"INFO_EMAIL_PASSWORD=${{secrets.INFO_EMAIL_PASSWORD}}" \
"INFO_EMAIL_IMAP_ADDRESS=${{secrets.INFO_EMAIL_IMAP_ADDRESS}}" \
"INFO_EMAIL_IMAP_PORT=${{secrets.INFO_EMAIL_IMAP_PORT}}" \
"PETEXEC_USERNAME=${{secrets.PETEXEC_USERNAME}}" \
"PETEXEC_PASSWORD=${{secrets.PETEXEC_PASSWORD}}" \
"PETEXEC_CLIENTID=${{secrets.PETEXEC_CLIENTID}}" \
"PETEXEC_CLIENTSECRET=${{secrets.PETEXEC_CLIENTSECRET}}" \
"PETEXEC_SCOPES=${{secrets.PETEXEC_SCOPES}}" \
>> .env
